// `script` driver — for scenarios whose load is generated by a standalone
// Node script (fanout-bench.js, etc.) rather than artillery. Flow:
//
//   1. ensureAppDeps  → npm install if the app's node_modules is missing
//   2. resetMeteorApp → meteor reset to start from a known state
//   3. prepareGcOutput → carve a temp file path that the gc-monitor
//      (--require'd into the Meteor process) will write to on SIGTERM
//   4. startMeteorApp → spawn `meteor run`, returns { proc, getRuntimeInfo }
//   5. waitForApp → poll the port until the app answers 2xx
//   6. startCollectors → spawn process-monitor for APP + DB pids
//   7. Run the script via execFileSync (5-min timeout so a hung script
//      can't lock the harness forever)
//   8. Parse the LAST line of stdout as JSON — convention: scripts dump
//      one summary JSON line at the end. Earlier lines (logs) are ignored.
//   9. stopCollectors → SIGTERM the monitors, drain stdout, parse
//   10. stopMeteorApp → SIGTERM Meteor, give it 3s to flush GC monitor
//   11. drainPostStopGc → pick up the GC file if it arrived during shutdown
//   12. Build + return the result; caller writes to disk.

import path from 'node:path';
import { io } from '../runner/_io.js';
import {
  ensureAppDeps,
  resetMeteorApp,
  startMeteorApp,
  stopMeteorApp,
} from '../runner/meteor-process.js';
import { waitForApp } from '../runner/wait-for-app.js';
import {
  prepareGcOutput,
  prepareMethodTimingOutput,
  prepareSubTimingOutput,
  preparePropagationTimingOutput,
  prepareObserverPoolOutput,
  prepareDdpMessageOutput,
  prepareFrameSizeOutput,
  prepareCompressionOutput,
  prepareDriverFallbackOutput,
  startCollectors,
  stopCollectors,
  drainPostStopGc,
} from '../runner/collectors.js';
import { buildResult } from '../reporters/json-reporter.js';

const HERE = import.meta.dirname;
const SCRIPT_TIMEOUT_MS = 300_000;

export async function runScriptDriver({ scenario, scenarioName, app, appName, source, env, tag, config }) {
  ensureAppDeps(app.path);
  resetMeteorApp(source, app.path);

  const { gcMonitorPath, gcOutputPath } = prepareGcOutput(tag);
  const methodTimingPath = prepareMethodTimingOutput(tag);
  const subTimingPath = prepareSubTimingOutput(tag);
  const propagationTimingPath = preparePropagationTimingOutput(tag);
  const observerPoolPath = prepareObserverPoolOutput(tag);
  const ddpMessagePath = prepareDdpMessageOutput(tag);
  const frameSizePath = prepareFrameSizeOutput(tag);
  const compressionPath = prepareCompressionOutput(tag);
  const driverFallbackPath = prepareDriverFallbackOutput(tag);

  console.log('Starting Meteor app...');
  const { proc: meteorProc, getRuntimeInfo } = startMeteorApp({
    source, appPath: app.path, port: config.appPort, env, gcMonitorPath, gcOutputPath, methodTimingPath, subTimingPath, propagationTimingPath, observerPoolPath, ddpMessagePath, frameSizePath, compressionPath, driverFallbackPath,
  });

  console.log('Waiting for app to start...');
  await waitForApp(config.appPort);
  console.log('App started.');

  const mongoUri = process.env.BENCH_MONGO_URL || `mongodb://127.0.0.1:${config.appPort + 1}`;
  const collectors = startCollectors({ appName, mongoUri, gcOutputPath, methodTimingPath, subTimingPath, propagationTimingPath, observerPoolPath, ddpMessagePath, frameSizePath, compressionPath, driverFallbackPath });

  const scriptPath = path.resolve(HERE, '..', scenario.script);
  const scriptArgs = (scenario.args || '').split(/\s+/).filter(Boolean);
  console.log(`\nRunning: node ${scenario.script} ${scenario.args || ''}\n`);

  const scriptStart = Date.now();
  let scriptOutput = '';
  try {
    scriptOutput = io.execFileSync('node', [scriptPath, ...scriptArgs], {
      cwd: path.resolve(HERE, '..'),
      encoding: 'utf8',
      env: { ...process.env },
      stdio: ['ignore', 'pipe', 'pipe'],
      timeout: SCRIPT_TIMEOUT_MS,
    });
  } catch (err) {
    console.error('Script failed:', err.stderr || err.message);
    scriptOutput = err.stdout || '';
  }
  const wallClockMs = Date.now() - scriptStart;

  // Convention: scripts emit human-readable logs throughout and one final
  // JSON summary line at the end. We grab `.pop()` after split('\n') to
  // get that line. If it fails to parse we keep scriptMetrics = {} so the
  // result JSON still has the right shape (with `fanout` metric just empty).
  let scriptMetrics = {};
  const jsonLine = scriptOutput.trim().split('\n').pop();
  if (jsonLine) {
    try {
      scriptMetrics = JSON.parse(jsonLine);
    } catch (err) {
      console.error(`Could not parse script metrics JSON from last stdout line: ${err.message}. Last line was: ${jsonLine.slice(0, 200)}`);
    }
  }

  const collectorResults = await stopCollectors(collectors);
  await stopMeteorApp(meteorProc);
  collectorResults.push(...drainPostStopGc(gcOutputPath));
  collectorResults.push({ metric: 'fanout', ...scriptMetrics });

  if (scriptMetrics.fanout_avg_ms) {
    console.log(`Fanout: avg=${scriptMetrics.fanout_avg_ms}ms p50=${scriptMetrics.fanout_p50_ms}ms p95=${scriptMetrics.fanout_p95_ms}ms max=${scriptMetrics.fanout_max_ms}ms`);
  }

  return buildResult({
    scenario: scenarioName,
    app: appName,
    tag,
    meteor: { version: source.version, sha: source.sha },
    runtime: getRuntimeInfo(),
    collectorResults,
    wallClockMs,
  });
}
